name: MoPets
version: '${project.version}'
main: mv.mossuh.mopets.MoPets
api-version: '1.13'

depend:
  - MoCore
  - NBTAPI

softdepend:
  - MoBoosters
  - PlaceholderAPI

commands:
  mopets:
    aliases:
      - mopet